variables:
  # B101    assert_used
  # B104    hardcoded_bind_all_interfaces
  # B108    hardcoded_tmp_directory
  # B605    start_process_with_a_shell
  # B602    subprocess_popen_with_shell_equals_true
  BANDIT_SKIPS: 'B101,B104,B108,B605,B602'

  CI_REGISTRY_IMAGE: registry.gitlab.isc.org/isc-projects/forge

bandit:
  image: "${CI_REGISTRY_IMAGE}:latest"
  script:
    - bandit -s "${BANDIT_SKIPS}" -r ./forge ./tests

pylint:
  image: "${CI_REGISTRY_IMAGE}:latest"
  script:
    - . ./activate-venv.sh
    - ./check-style.sh

semgrep:
  allow_failure: true
  image: "${CI_REGISTRY_IMAGE}:latest"
  script:
    - semgrep --config auto --error .
