variables:
  CI_REGISTRY_IMAGE: registry.gitlab.isc.org/isc-projects/forge

image: "${CI_REGISTRY_IMAGE}:latest"

.rules: &rules
  rules:
    # Do not run on MR creation.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    # Run on any other event, including push to MR branch and push to master.
    - when: always

.get_modified_python_scripts: &get_modified_python_scripts
  - |
    MODIFIED_PYTHON_SCRIPTS=
    for i in $(git diff --name-only $(git merge-base origin/master HEAD)); do
      if echo ${i} | grep -E '.py$' > /dev/null 2>&1; then
        if ! echo ${PYTHON_EXCLUDE} | grep -F "${i}" > /dev/null 2>&1; then
          MODIFIED_PYTHON_SCRIPTS+=" ${i}"
        fi
      fi
    done
    if test -z "${MODIFIED_PYTHON_SCRIPTS}"; then
      echo "No python scripts to check. Exiting early."
      exit 0
    else
      echo "Checking python scripts: ${MODIFIED_PYTHON_SCRIPTS}"
    fi

bandit:
  <<: *rules
  script:
    - *get_modified_python_scripts
    - ./check-style.sh --bandit ${MODIFIED_PYTHON_SCRIPTS}

pages:
  rules:
    # Deploy docs only on merge to master.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
  script:
    # Add __init__.py files.
    - touch __init__.py
    - >
      find ./* -type d
      -not -path './dhcp/burnin/scripts/tci*'
      -not -path './unused/performance/charts*'
      -exec touch {}/__init__.py ';'
    # Generate docs.
    - pydoctor --docformat restructuredtext --html-output public .
  artifacts:
    paths:
      - public

pycodestyle:
  <<: *rules
  script:
    - *get_modified_python_scripts
    - ./check-style.sh --pycodestyle ${MODIFIED_PYTHON_SCRIPTS}

pydocstyle:
  <<: *rules
  script:
    - *get_modified_python_scripts
    - ./check-style.sh --pydocstyle ${MODIFIED_PYTHON_SCRIPTS}

pydoctor:
  <<: *rules
  script:
    - *get_modified_python_scripts
    - ./check-style.sh --pydoctor ${MODIFIED_PYTHON_SCRIPTS}

pylint:
  <<: *rules
  script:
    - *get_modified_python_scripts
    - ./check-style.sh --pylint ${MODIFIED_PYTHON_SCRIPTS}

